apiVersion: v1
kind: ConfigMap
metadata:
  name: pronunt-frontend-service-config
  namespace: pronunt-app-ns
data:
  NEXT_PUBLIC_AGGREGATOR_API_URL: http://pronunt-aggregator-service:8000
  NEXT_PUBLIC_APP_NAME: PRISM
  NEXT_TELEMETRY_DISABLED: "1"


